### ISSUE TITLE
SVN::Look fails on filenames ending in space characters

### ISSUE THREAD

**Issue by stephane-chazelas** [gnustavo/SVN-Look#4]
I was trying to add a pre-commit hook that refused filenames ending in space characters as those are not supported on Microsoft operating systems, but the hook let them through.

It appears it is because `SVN::Look` trims the spaces at the end of the filenames from the output of `svnlook changed`.

That's because the output is parsed with:

```
    my ($action, $prop, undef, undef, $changed) = unpack 'AAAA A*', $_;
```

`A*` removes the trailing blanks. The fix would be something like:

``` diff
--- /usr/share/perl5/SVN/Look.pm~2  2014-06-04 12:48:53.117317732 +0100
+++ /usr/share/perl5/SVN/Look.pm    2014-06-04 12:48:12.580330024 +0100
@@ -118,7 +118,7 @@ sub changed_hash {
         foreach ($self->_svnlook('changed', '--copy-info')) {
             next if length($_) <= 4;
             chomp;
-            my ($action, $prop, undef, undef, $changed) = unpack 'AAAA A*', $_;
+            my ($action, $prop, $changed) = unpack 'AAxx a*', $_;
             if    ($action eq 'A') {
                 push @added,   $changed;
             }
```

**Comment by gnustavo** [comment]
Thank you. I've applied your fix in the just released version 0.40.
