### ISSUE TITLE
ExtUtils-MakeMaker-7.48 rejects invalid MIN_PERL_VERSION values

### ISSUE THREAD

**Issue by ppisar** [gnustavo/SVN-Look#5]
Building with ExtUtils-MakeMaker-7.48 fails. See <https://rt.cpan.org/Ticket/Display.html?id=133489>.  A change like this in the generated Makefile.PL fixes it:

~~~~
-  'MIN_PERL_VERSION' => '5.008_000',
+  'MIN_PERL_VERSION' => '5.008000',
~~~~

**Comment by gnustavo** [comment]
Thanks, @ppisar .

I just released version 0.42 which should fix this.
